package modelo;
// Generated 4 ene 2022 0:52:55 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private int codUsuario;
	private String nombre;
	private String password;
	private Set espaciosNaturaleses = new HashSet(0);
	private Set municipioses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(int codUsuario, String nombre, String password) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.password = password;
	}

	public Usuarios(int codUsuario, String nombre, String password, Set espaciosNaturaleses, Set municipioses) {
		this.codUsuario = codUsuario;
		this.nombre = nombre;
		this.password = password;
		this.espaciosNaturaleses = espaciosNaturaleses;
		this.municipioses = municipioses;
	}

	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getEspaciosNaturaleses() {
		return this.espaciosNaturaleses;
	}

	public void setEspaciosNaturaleses(Set espaciosNaturaleses) {
		this.espaciosNaturaleses = espaciosNaturaleses;
	}

	public Set getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set municipioses) {
		this.municipioses = municipioses;
	}

}
