package modelo.dbClasses;
// Generated 4 ene 2022 0:52:55 by Hibernate Tools 5.5.7.Final

import java.time.LocalDate;
import java.time.LocalTime;

import org.json.simple.JSONObject;

import modelo.jsonSerializable;

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable, jsonSerializable {

	private DatosId id;
	private Estaciones estaciones;
	private Double comgm3;
	private Double co8hmgm3;
	private Double nogm3;
	private Double no2gm3;
	private String no2ICA;
	private Double noxgm3;
	private Double pm10gm3;
	private String pm10ICA;
	private Double pm25gm3;
	private String pm25ICA;
	private Double so2gm3;
	private String so2ICA;
	private String estacionICA;
	public Datos() {
	}

	public Datos(DatosId id) {
		this.id = id;
	}
	
	public Datos(DatosId id, Estaciones estaciones, int temperatura, int velocidadViento) {
		this.id = id;
		this.estaciones = estaciones;
	}

	public Datos(DatosId id, Estaciones estaciones,
			Double comgm3, Double co8hmgm3, Double nogm3, Double noxgm3, Double pm10gm3, Double pm25gm3,
			Double so2gm3) {
		this.id = id;
		this.estaciones = estaciones;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.noxgm3 = noxgm3;
		this.pm10gm3 = pm10gm3;
		this.pm25gm3 = pm25gm3;
		this.so2gm3 = so2gm3;
	}

	public DatosId getId() {
		return this.id;
	}

	public void setId(DatosId id) {
		this.id = id;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	// COmgm3
	
	public Double getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(Double comgm3) {
		this.comgm3 = comgm3;
	}
	
	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setComgm3(JSONObject datosJSON, String datoKey) {
     	String cOmgm3 = (String) datosJSON.get(datoKey);
     	if(cOmgm3 != null) {
     		cOmgm3 = cOmgm3.replaceAll(",", ".");
     		this.setComgm3( Double.parseDouble(cOmgm3) );
     	}
	}

	// CO8hmgm3

	public Double getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(Double co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}
	
	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setCo8hmgm3(JSONObject datosJSON, String datoKey) {
     	String co8hmgm3 = (String) datosJSON.get(datoKey);
     	if(co8hmgm3 != null) {
     		co8hmgm3 = co8hmgm3.replaceAll(",", ".");     		
     		this.setCo8hmgm3( Double.parseDouble(co8hmgm3) );
     	}
	}

	
	// NOgm3
	public Double getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(Double nogm3) {
		this.nogm3 = nogm3;
	}
	
	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setNogm3(JSONObject datosJSON, String datoKey) {
     	String nogm3 = (String) datosJSON.get(datoKey);
     	if(nogm3 != null) {
     		nogm3 = nogm3.replaceAll(",", ".");     		
     		this.setNogm3( Double.parseDouble(nogm3) );

     	}
	}
	
	// NO2gm3	
	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setNo2gm3(JSONObject datosJSON, String datoKey) {
     	String no2gm3 = (String) datosJSON.get(datoKey);
     	if(no2gm3 != null) {
     		no2gm3 = no2gm3.replaceAll(",", ".");     		
     		this.setNo2gm3( Double.parseDouble(no2gm3) );

     	}
	}

	// NOXgm3
	
	public Double getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(Double noxgm3) {
		this.noxgm3 = noxgm3;
	}
	
	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setNoxgm3(JSONObject datosJSON, String datoKey) {
     	String noxgm3 = (String) datosJSON.get(datoKey);
     	if(noxgm3 != null) {
     		noxgm3 = noxgm3.replaceAll(",", ".");     		
     		this.setNoxgm3( Double.parseDouble(noxgm3) );
     	}
	}
	
	
	// PM10gm3

	public Double getPm10gm3() {
		return this.pm10gm3;
	}

	public void setPm10gm3(Double pm10gm3) {
		this.pm10gm3 = pm10gm3;
	}

	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setPm10gm3(JSONObject datosJSON, String datoKey) {
     	String pm10gm3 = (String) datosJSON.get(datoKey);
     	if(pm10gm3 != null) {
     		pm10gm3 = pm10gm3.replaceAll(",", ".");     		
     		this.setPm10gm3( Double.parseDouble(pm10gm3) );
     	}
	}

	
	// PM25gm3
	
	public Double getPm25gm3() {
		return this.pm25gm3;
	}

	public void setPm25gm3(Double pm25gm3) {
		this.pm25gm3 = pm25gm3;
	}

	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setPm25gm3(JSONObject datosJSON, String datoKey) {
     	String pm25gm3 = (String) datosJSON.get(datoKey);
     	if(pm25gm3 != null) {
     		pm25gm3 = pm25gm3.replaceAll(",", ".");     		
     		this.setPm25gm3( Double.parseDouble(pm25gm3) );
     	}
	}
	
	// SO2gm3
	
	public Double getSo2gm3() {
		return this.so2gm3;
	}

	public void setSo2gm3(Double so2gm3) {
		this.so2gm3 = so2gm3;
	}
	
	/**
	 * Setter diseñado para recoger el atributo desde una url del index.json
	 * @param datosJSON
	 * @param datoKey
	 */
	public void setSo2gm3(JSONObject datosJSON, String datoKey) {
     	String so2gm3 = (String) datosJSON.get(datoKey);
     	if(so2gm3 != null) {
     		so2gm3 = so2gm3.replaceAll(",", ".");     		
     		this.setSo2gm3( Double.parseDouble(so2gm3) );
     	}
	}

	public LocalDate getFecha() {
		return this.id.getFecha();
	}
	
	public LocalTime getHora() {
		return this.id.getHora();
	}
	
	public Double getNo2gm3() {
		return no2gm3;
	}

	public void setNo2gm3(Double no2gm3) {
		this.no2gm3 = no2gm3;
	}

	public String getNo2ICA() {
		return no2ICA;
	}

	public void setNo2ICA(String no2ica) {
		no2ICA = no2ica;
	}

	
	public String getPm10ICA() {
		return pm10ICA;
	}

	public void setPm10ICA(String pm10ica) {
		pm10ICA = pm10ica;
	}


	public String getPm25ICA() {
		return pm25ICA;
	}

	public void setPm25ICA(String pm25ica) {
		pm25ICA = pm25ica;
	}

	public String getSo2ICA() {
		return so2ICA;
	}

	public void setSo2ICA(String so2ica) {
		so2ICA = so2ica;
	}

	public String getEstacionICA() {
		return estacionICA;
	}

	public void setEstacionICA(String estacionICA) {
		this.estacionICA = estacionICA;
	}

	@Override
	public String toJSON() {
		return "{\"estacionICA\":\""+estacionICA+"\","
				+ "\"comgm3\":\""+comgm3+"\","
				+ "\"fecha\":\""+id.getFecha()+"\","
				+ "\"hora\":\""+id.getHora()+"\"}";
	}


}
