package modelo.dbClasses;
// Generated 4 ene 2022 0:52:55 by Hibernate Tools 5.5.7.Final

/**
 * Hashes generated by hbm2java
 */
public class Hashes implements java.io.Serializable {

	private String codHash;
	private String url;

	public Hashes() {
	}

	public Hashes(String codHash, String url) {
		this.codHash = codHash;
		this.url = url;
	}

	public String getCodHash() {
		return this.codHash;
	}

	public void setCodHash(String codHash) {
		this.codHash = codHash;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
