-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 06-01-2022 a las 23:57:58
-- Versión del servidor: 10.4.21-MariaDB
-- Versión de PHP: 7.3.31

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `euskalmet`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `espacios_naturales`
--

--
-- Volcado de datos para la tabla `espacios_naturales`
--

INSERT INTO `espacios_naturales` (`CodEspacio`, `Nombre`, `Descripcion`) VALUES
(1, 'Piscinas fluviales de Espejo', 'Las piscinas fluviales de Espejo se hallan en el territorio histórico de Álava, en el municipio de Valdegovía, dentro de la Cuadrilla de Añana. Este bello entorno, emplazado en el río Omecillo, se convierte en lugar de descanso para muchos lugareños y visitantes durante los meses de verano. Cuenta con amplios aparcamientos a ambos lados del río, una zona de baño y un área de recreo con arbolado que dispone de asadores, mesas, bancos e instalaciones infantiles para el disfrute de los más pequeños. Además, en el río también existen tramos preparados para los aficionados al piragü ismo.'),
(2, 'Playa de Arrigunaga', 'La playa de Arrigunaga se encuentra en el municipio de Getxo, en Bizkaia. Ubicada bajo los acantilados de La Galea, ofrece hermosas vistas al Abra y al Molino de Aixerrota. Además de poder tomar el sol y un agradable baño, la playa de Arrigunaga ofrece al visitante la posibilidad de realizar numerosas actividades como elsurfo el skate. Aunque es de fácil acceso, resulta algo peligrosa, ya que su fondo es de arena y roca, y al bajar la marea, aparecen puntas de roca, por lo que hay que tener cuidado. Genera varias olas a lo largo de la playa, siendo las más interesantes las que rompen atrás. En la zona oeste de la playa hay un espigón y junto a él, los días de mucho mar rompe una derecha que se adentra en la ría. Esta ola es sólo para expertos ya que rompe a partir de los dos metros de altura. A un kilómetro más hacia el norte se encuentra otra ola de gran calidad que solo rompe en ocasiones especiales, se trata de unpoint breakque genera largas derechas. Cabe destacar que este arenal ha obtenido laBandera Azul, Certificado Internacional de Calidad Ambiental otorgado por la FEE'),
(3, 'Playa de Barinatxe', 'Enclavada entre los municipios vizcaínos de Sopela y Getxo, la playa de Barinatxe está compuesta por tres elementos vitales de la naturaleza: agua de una inmensa bravura, fina arena y un aire volátil que emana una pureza solamente propia de enclaves tan característicos como este. Precisamente gracias a su innato e impredecible ecosistema, Barinatxe se ha ganado el nombre de “ La Salvaje&rdquor . Se trata de unaplaya amplia y abierta, flanqueada por hermosos acantilados, y que cuenta con una zona naturista. Asimismo, la playa de Barinatxe ofrece la oportunidad de realizar numerosas actividades, entre las que destaca elsurf, debido al gran oleaje de sus aguas. Como su propio nombre indica se trata de una playa salvaje con un sistema dunar propio. Cuenta con un edificio multiusos con vestuarios, duchas y donde tienen su sede las escuelas de surf locales, cuenta con dos clubes de surf y como el resto de las playas de esta zona hay una gran afluencia de bañistas y surfistas. Orientada al noroeste, la frecuencia de olas es bastante alta. Es una playa que cuenta con distintos picos, la más conocida es la ola de La Triangular, de fondo rocoso, que puede aguantar bastante tamaño y funciona con todas las mareas. Se trata de una derecha larga con un pico muy concentrado pero bastante noble, lo que la hace ideal para la práctica del longboard, en marea baja tiene una izquierda más vertical con secciones tuberas. En la zona oeste de la playa está la ola de La Batidora, donde predominan las izquierdas. En la zona centro se encuentra La Corriente, una izquierda muy técnica y muy cambiante en función de la marea, el tamaño del swell y la corriente. En Barinatxe los fondos son muy cambiantes y pueden dar olas de mucha calidad. Sus acantilados son ideales para la práctica del parapente.'),
(4, 'Playa de Ereaga', 'La playa de Ereaga se encuentra en el municipio de Getxo, entre el puerto viejo de Algorta y el espigón de Arriluze. Con sus más de800 metros de fina arena, este hermoso arenal está muy bien equipado de cara a la época estival. Por otro lado, son muchos los deportes que se practican en esta playa: surf, piragü ismo, voleibol y vela, entre otros. Pero, sin duda, Ereaga es muy conocida por los torneos de fútbol playa que aquí se disputan. Se trata de una playa urbana que ofrece sobre todo olas de izquierdas y es idónea para la práctica del bodyboard. Olas cortas y tubulares. Necesita mucho mar, por lo que no ofrece olas a menudo aguanta olas de hasta 2 metros y cabe destacar que está muy protegida del viento noroeste, por lo que resulta una alternativa muy válida cuando las condiciones meteorológicas son adversas en las playas abiertas y el mar está desfasado. El otro spot existente en esta playa es el apodado Jeffrey\'s por los locales: una derecha de calidad que rompe en la zona interna de la ría de Bilbao, en frente del Puerto Viejo de Algorta. Necesita de mucha mar para empezar a romper y son pocas las veces que lo hace al año, pero cuando se dan las condiciones, aguanta olas largas de hasta 3 metros de altura. El acceso es complicado ya que hay que acceder entre rocas o realizar una remada de mucho recorrido. Cabe destacar que este arenal ha obtenido laBandera Azul, Certificado Internacional de Calidad Ambiental otorgado por la FEE'),
(5, 'Playa de Gorrondatxe (Azkorri)', 'Gorrondatxe es la cuarta playa de Getxo  y  quizá la menos accesible, pero la más limpia. Conocido también por el nombre de Azkorri, este arenal se encuentra alejado del casco urbano del municipio al que pertenece, pero próximo a la vecina localidad de Berango.\r\n \r\nLa playa está situada en un entorno natural de excepción, rodeada de abruptos acantilados y hermosas dunas. De arena fina y oscura, está bien equipada.\r\n \r\nAsimismo, la playa de Gorrondatxe es un lugar propicio para la práctica de algunas actividades deportivas, como el voleibol y el surf.\r\n \r\nSe trata de una de las playas más especiales de la zona, es de las pocas que aún conserva el sistema dunar propio y es un beach rock, su superficie es dura. En la zona oeste de la playa se encuentra la ola del Akanti, justo enfrente de la punta del acantilado, es una izquierda muy técnica con distintas secciones, alguna de ellas tubera. Puede aguantar hasta 3 metros y necesita un swell medio para empezar a funcionar. En la zona centro y este de la playa también hay olas interesantes que rompen sobre roca, una derecha intensa y una izquierda de mayor calidad. En ambas olas es importante que las condiciones de viento y swell sean lo más limpias posible.\r\n \r\nCabe destacar que este arenal ha obtenido la Bandera Azul, certificado Internacional de Calidad Ambiental otorgado por la FEE.'),
(6, 'Playa de Hondarribia', 'La playa de Hondarribia está ubicada en el extremo oriental del litoral guipuzcoano, concretamente en la hermosa bahía de Txingudi, junto a la desembocadura del río Bidasoa.\n \nEste hermoso arenal defina arena dorada y aguas tranquilas cuenta con 700 metros de longitud. Se encuentra muy cerca del centro urbano, por lo que está rodeado de numerosos establecimientos hosteleros y dispone de diversos servicios.\n \nHondarribia es un spot alternativo para los días de maretón. Se trata de una derecha larga y maniobrable que rompe junto al espigón y da buenas sesiones, sobre todo en invierno. Único spot del municipio, es uno de los más bellos de la costa vasca.\n \nAsimismo, en esta playa, podemos practicar otros deportes acuáticos, entre los que destacan el piragü ismo y el windsurf. Además, durante la época estival, se coloca una estructura en el mar con toboganes y trampolines.'),
(7, 'Playa de Hondartzape', 'La playa de Hondartzape está ubicada en el municipio vizcaíno de Mundaka, a 36 km de Bilbao. La principal característica de esta playa son sus rocas y su arena negra, formando así, en bajamar, unapequeña y bonita cala. La playa cuenta en sus inmediaciones con unasespectaculares vistas, dado que se encuentra dentro de la Reserva de la Biosfera de Urdaibai, espacio natural de gran interés por ser lugar de reposo e invernada de muchas especies de aves migratorias. Hondartzape es un lugar apropiado para quienes buscan unambiente tranquilo e idealpara los amantes delsubmarinismo.'),
(8, 'Playa de La Arena', 'Situada entre Muskiz y Zierbena, la hermosa playa de La Arena tiene 966 metros de longitud y esuno de los rincones preferidos de los surfistasde la Margen Izquierda del Gran Bilbao. Es la última playa de Euskadi en su límite oeste. Tiene fundamentalmente tres olas principales: la izquierda de Pobeña, en la zona oeste de la playa, el Centro y la derecha del Vivero, en la zona este de la playa. Es en el Centro donde se imparten las clases de surf, ya que los otros dos picos merecen especial atención por las fuertes corrientes. Todas las olas funcionan en todas las mareas, aunque Pobeña rompe mejor con marea baja, siendo una izquierda larga de gran calidad que puede ofrecer sesiones épicas. La playa aguanta hasta los 2 metros y no necesita mucho mar, gracias a que es un arenal abierto.'),
(9, 'Playa de La Concha', 'La incomparable playa de La Concha es una de las señas de identidad de San Sebastián. Situada en pleno centro de la ciudad, ofrece al visitante la oportunidad de disfrutar de magníficas vistas, como la que nos ofrece su hermosa bahía en forma de concha, con la isla de Santa Clara en el centro, flanqueada por los montes Urgull e Igeldo.\n \nDefina arena dorada, en sus 1.350 metros de longitud podemos practicar numerosas actividades deportivas, tales como surf, windsurf, piragü ismo, bodyboard, voleibol o fútbol playa. Es un spot alternativo para los días grandes, un beach break  muy urbano. Cuenta con varios picos, sobre todo derechas, destacando El Pico del Loro en marea alta, ideal para la práctica de bodyboard.\n \nEn la temporada de verano, se coloca una estructura en el mar con toboganes y trampolines, que nos permite disfrutar aún más del baño. '),
(10, 'Playa de Laidatxu', 'La playa de Laidatxu se halla en el municipio vizcaíno deMundaka, muy cerca delcasco urbano. De dimensiones pequeñas yarena fina y dorada, la calidad de sus aguas es muy buena, por lo que es muy recomendable para familias con niños.\n \nConsiderada como una de las 10 mejores olas del mundo, Mundaka ofrece olas izquierdas de gran nivel, aptas sólo para surfistas con conocimientos altos. Necesita condiciones muy especiales. Su ola, espectacularmente tubular, se caracteriza además por su gran longitud. Puede aguantar hasta los 4 metros.\n \nSu situación en la salida de la ría de Gernika, hace que sus fondos no sean constantes y que cambien a lo largo del año. Enclavada en laReserva de la Biosfera Urdaibai, declarada patrimonio de la humanidad por la UNESCO, es uno de los parajes más espectaculares de la costa vasca.\n \nLa playa de Mundaka alberga importantes eventos de nivel mundial. Este pequeño arenal ofrece también la posibilidad de realizar otras actividades, como piragü ismo, windsurf... En la temporada de verano, podemos tomar un ferry para trasladarnos hasta la cercana playa de Laida, y recorrer así parte de la hermosa Reserva de la Biosfera de Urdaibai.'),
(11, 'Playa de Las Arenas', 'La playa de Las Arenas se encuentra en el municipio vizcaíno deGetxo, en el Abra de Bilbao, junto al muelle de Churruca y muy próxima alPuente de Bizkaia, monumento declarado Patrimonio de la Humanidad.\n \nEste pequeño arenal, ubicado en pleno centro urbano, está bien comunicado y cuenta en sus inmediaciones con un club marítimo de gran tradición y numerosos servicios hosteleros.\n \nEn la época estival, socorristas y hondartzainas vigilan la playa, mientras que los usuarios tienen a su disposición varios servicios aseos, duchas, vestuarios, fuentes... Además de ser un lugar propicio para tomar el sol, esta playa ofrece la posibilidad de realizar diversas actividades, como windsurf, piraguismo y, en especial,vela.\n \nCerca se encuentra la escuela de vela José Luis de Ugarte, donde se organizan cursos de iniciación y perfeccionamiento en este deporte a partir de los ocho años, entre otras actividades.'),
(12, 'Playa de Ondarreta', 'Situada en el extremo oeste de la capital donostiarra, al abrigo del monte Igeldo y frente a la isla de Santa Clara, esta playa de fina arena dorada es una de las más elegantes de Gipuzkoa. Ondarreta, con sus 600 metros de longitud, dispone de una variada oferta deportiva. Durante los meses de verano, se organizan cursos de natación y voleibol. Asimismo, es posible practicar numerosas actividades acuáticas y posee, además, amplias y modernas instalaciones. Ondarreta cuenta con un par de izquierdas que rompen junto al paseo oeste de la playa. Izquierdas rápidas e intensas. Es un spot alternativo para los días de maretón y condiciones adversas, está protegida de los vientos del oeste. De gran vistosidad ya que los paseantes están literalmente encima de los surfistas. Precisamente, está unida a las playas de La Concha y La Zurriola a través de un paseo marítimo de 7 kilómetros que termina cerca de Ondarreta, en el Peine del Viento, espacio mágico donde contemplaremos las esculturas de acero de Eduardo Chillida que se agarran a las rocas, desafiando a las olas del mar.'),
(13, 'Playa de Zarautz', 'La playa de Zarautz llama especialmente la atención por su extensa longitud, con 2.500 metros de fina arena dorada.\n \nEste hermoso arenal, con sus llamativos toldos, cuenta con un animado paseo marítimo repleto de bares, cafeterías y restaurantes. La playa está abierta al mar y es muy conocida por las olas que allí se forman, pues sirven de reclamo para surfistas que provienen de muchos lugares del mundo. De hecho, Zarautz posee una de las mejores canteras de surfistas de toda Europa.\n \nEs la playa más extensa de la costa vasca y cuenta con multitud de rompientes. Es ideal para la iniciación en el surf y cuenta con cinco escuelas, su club de surf es uno de los más activos de la costa. Alberga varias competiciones a lo largo del año, destacando el mundial WQS que se celebra en el mes de septiembre. De oeste a este destacan los picos del puerto, (el cual rompe cuando hay mar de más de dos metros) Argiñano, verdadero epicentro de la playa y El canal, una zona más alejada en la punta este que da sesiones de calidad.\n \nEl ambiente surfero de Zarautz es increíble, destacando las zonas de Argiñano y el pueblo.'),
(14, 'Playa de la Zurriola', 'La playa de la Zurriola se halla en el barrio donostiarra de Gros, bajo la atenta mirada del Palacio de Congresos y Auditorio Kursaal. Antiguamente, estuvo formada por grandes arenales ubicados entre la desembocadura del río Urumea y el monte Ulía. En la década de los 90, comenzaron los trabajos de rehabilitación y se procedió a la construcción de la actual playa, defina arena dorada y fuerte oleaje. La playa más surfera de la capital, cuenta con olas de calidad, destacando la derecha de Monpas y El Centro, con derechas e izquierdas intensas. Monpas puede generar buenas secciones tuberas y es la ola de más fuerza, mientras que El Centro genera principalmente izquierdas en marea baja y buenas derechas a medida que sube la marea. Es una playa que recoge mucho mar y funciona en todas las mareas. En esta playa se desarrollan importantes eventos de surf como la prueba europea Projunior ASP que se celebra en julio. La playa cuenta con unclub de surf local y cuatro escuelas de surf, por lo que es ideal para la iniciación.'),
(15, 'Zierbena-Puerto', 'Situada en la costa occidental de Bizkaia, esta playa artificial de tan sólo 100 metros de longitud se encuentra en el propio puerto pesquero de Zierbena. Esta pequeña playa se asoma en bajamar. Sus aguas tranquilas son seguras para los bañistas y sobre todo, para los más pequeños. En verano, dispone de varios servicios, como duchas, hondartzainas, socorristas... El lugar mantiene su encanto y cierto sabor marinero, con barcos de pesca y de recreo atracados en el puerto y los típicos restaurantes y asadores en las inmediaciones que despiden un delicioso aroma de pescados cocinados a la brasa. Además de poder tomar el sol y un agradable baño, la playa de Zierbena ofrece al visitante la posibilidad de realizar actividades como piragü ismo y vela.');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `espacios_naturales`
--
ALTER TABLE `espacios_naturales`
  ADD PRIMARY KEY (`CodEspacio`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
