package primero;
// Generated 2 dic 2021 20:38:09 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idventa;
	private Clientes clientes;
	private Productos productos;
	private Date fechaventa;
	private byte cantidad;

	public Ventas() {
	}

	public Ventas(short idventa, Clientes clientes, Productos productos, Date fechaventa, byte cantidad) {
		this.idventa = idventa;
		this.clientes = clientes;
		this.productos = productos;
		this.fechaventa = fechaventa;
		this.cantidad = cantidad;
	}

	public short getIdventa() {
		return this.idventa;
	}

	public void setIdventa(short idventa) {
		this.idventa = idventa;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	public Date getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	public byte getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(byte cantidad) {
		this.cantidad = cantidad;
	}

}
